name: "UI Tests"

on:
  workflow_dispatch:
  schedule:
    - cron: '00 02 * * *'

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      WAS_EDITED: ${{ steps.check_date.outputs.WAS_EDITED }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - id: check_date
        name: Check if there were commits in the last day
        run: echo '::set-output name=WAS_EDITED::'$(test -n "$(git log --format=%H --since='25 hours ago')" && echo 'true' || echo 'false')
  ui_tests:
    runs-on: macos-latest
    needs: [check_date]
    if: ${{ needs.check_date.outputs.WAS_EDITED == 'true' }}
    timeout-minutes: 45
    strategy:
      matrix:
        # test on the minimum and on a more recent version
        android: [ 21, 33 ]
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Display branch name
        run: |
          echo "current branch: $GITHUB_REF"
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true
      - name: Set up Gradle cache
        uses: actions/cache@v3
        id: gradle-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.android }}
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.26.0
        with:
          api-level: ${{ matrix.android }}
          # use target "google_apis" because there are no "default" images for recent Android versions
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: >-
            -no-boot-anim -no-audio -no-snapshot -no-window -camera-back none
            -camera-front none -gpu swiftshader_indirect
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: "UI Tests"
        uses: reactivecircus/android-emulator-runner@v2.26.0
        with:
          api-level: ${{ matrix.android }}
          # use target "google_apis" because there are no "default" images for recent Android versions
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: >-
            -no-snapshot-save -no-boot-anim -no-audio -no-snapshot -no-window -camera-back none
            -camera-front none -gpu swiftshader_indirect
          disable-animations: true
          script: ./gradlew connectedAndroidTest --no-daemon --info
